CREATE TABLE `diagnosticos_qualidade` (
	`id` text PRIMARY KEY NOT NULL,
	`ativo_dados_id` text NOT NULL,
	`demanda_id` text NOT NULL,
	`iniciado_em` text NOT NULL,
	`concluido_em` text,
	`duracao_ms` integer DEFAULT 0 NOT NULL,
	`total_linhas_avaliadas` integer DEFAULT 0 NOT NULL,
	`total_colunas_avaliadas` integer DEFAULT 0 NOT NULL,
	`verificacoes_executadas` text DEFAULT '[]' NOT NULL,
	`total_problemas_detectados` integer DEFAULT 0 NOT NULL,
	`status_execucao` text DEFAULT 'EM_ANDAMENTO' NOT NULL,
	`erro_mensagem` text,
	`resumo_metricas` text,
	`criado_em` text NOT NULL,
	`atualizado_em` text NOT NULL,
	FOREIGN KEY (`ativo_dados_id`) REFERENCES `ativos_dados`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`demanda_id`) REFERENCES `demandas`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `problemas_qualidade` (
	`id` text PRIMARY KEY NOT NULL,
	`diagnostico_id` text NOT NULL,
	`ativo_dados_id` text NOT NULL,
	`demanda_id` text NOT NULL,
	`categoria` text NOT NULL,
	`titulo` text NOT NULL,
	`descricao` text NOT NULL,
	`tabela_afetada` text NOT NULL,
	`coluna_afetada` text,
	`total_linhas_afetadas` integer DEFAULT 0 NOT NULL,
	`percentual_linhas_afetadas` real DEFAULT 0 NOT NULL,
	`amostra_evidencias` text DEFAULT '[]' NOT NULL,
	`severidade` text DEFAULT 'PENDENTE' NOT NULL,
	`impacto_calculo` text,
	`acao_deliberada` text,
	`justificativa_deliberacao` text,
	`deliberado_por_humano` integer DEFAULT 0 NOT NULL,
	`deliberado_em` text,
	`status` text DEFAULT 'ABERTO' NOT NULL,
	`origem_deteccao` text DEFAULT 'AUTOMATICA' NOT NULL,
	`criado_em` text NOT NULL,
	`atualizado_em` text NOT NULL,
	FOREIGN KEY (`diagnostico_id`) REFERENCES `diagnosticos_qualidade`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`ativo_dados_id`) REFERENCES `ativos_dados`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`demanda_id`) REFERENCES `demandas`(`id`) ON UPDATE no action ON DELETE cascade
);
